[project]
name = "download-dryad-dataset"
version = "0.1.0"
description = "A script to download datasets from Dryad."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests >= 2.32.5",
    "tqdm >= 4.67.1"
]
